## Data analyst

- SQL
- One shot Query
- Programmers - MNC (Maths And Computing)
- Power BI - Charts

Data Scientist

- Excel
- Line by line (Step)
- Python - numpy, pandas
    - Scales well and are open-source
- Scikit - Data prediction
- Matplot, seaborn - Charts

In [1]:
%pip install numpy

     ---------------------------------------- 6.0/6.0 MB 3.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## Numpy
- Work with Arrays
- Performant
- C language (faster)- Statisically oriented (mean, mode, std)

In [1]:
import numpy as np

## Shortcuts
- `ctrl+alt+enter` -> Run the cell
- `shift + enter` -> Move to next cell

In [5]:
marks = np.array([90, 80, 20, 40])
print(marks * 2)
marks_list = [90, 80, 20, 40]
marks_list_dbl = [num * 2 for num in marks_list]
print(marks_list_dbl)
marks_list* 2


[180 160  40  80]
[180, 160, 40, 80]


[90, 80, 20, 40, 90, 80, 20, 40]

In [8]:
np.ones(200) # Identity matrix
np.zeros(90)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [10]:
np.arange(10) # 0-9
np.arange(1, 10) # 1-9
np.arange(1, 10, 2) # 1, 3, 5, 7, 9

array([1, 3, 5, 7, 9])

In [11]:
np.arange(10) > 5 # apply condition on each value 1-9

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [12]:
np.arange(10) * 2 # multiply each value 1-9

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
first_ten_nums = np.arange(1, 11)
all_gt_five = first_ten_nums  > 5
# filters and gives a new list
print(first_ten_nums[all_gt_five])
# original list is unchanged
first_ten_nums

[ 6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Task
Create a 1..200 numbers and provide a numpy array with all even numbers

In [20]:
nums200 = np.arange(0, 201, 2) 
nums200

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

## Task 2 
Without the skip/step of arange

In [21]:
nums200 = np.arange(1, 201) 
# array of booleans
all_even = nums200 % 2 == 0
print(nums200[all_even])
nums200

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [42]:
# get 5 random int values between 18 and 60 in an array
ages = np.random.randint(18, 60, 5)
# ages # arrray([29, 36, 18, 34, 38])
ages_list = ages.tolist()
ages_list

[37, 40, 24, 46, 50]

In [73]:
# Evaluate performance
%time

double_ages = [age * 2 for age in ages_list]
print(double_ages)

CPU times: total: 0 ns
Wall time: 0 ns
[74, 80, 48, 92, 100]


In [72]:
%time

dbl_ages = ages * 2
dbl_ages

CPU times: total: 0 ns
Wall time: 0 ns


array([ 74,  80,  48,  92, 100])

## Statistically oriented (mean, mode, std)

- mean -> Average 
- model -> The most repeated number (most popular)
- median -> Middle most number

In [75]:
marks = np.random.randint(40, 100, 10)
print(marks)
print(marks.mean())
print(np.mean(marks))

[46 47 48 40 50 62 75 69 42 80]
55.9
55.9


In [76]:
np.median(marks)

49.0

In [77]:
np.sum(marks)

559

## Task 
Investment = R1000
Interest rate = 5%
At the end of 2 years what will the balance be?
1st year = R50 -> R1050
2cnd year = R52.5 -> R1102.5

In [102]:
list_of_values = []
def add_interest(value, years, interest_rate):
    for i in range(years):
        value = value * (1 + interest_rate)
        list_of_values.append(value)
        # print(list_of_values)
    return list_of_values
yearly_amounts = add_interest(1000, 10, 0.05)
print("Yearly changes")
print(yearly_amounts)

years = np.arange(1, 11)
yearly_return = 1000 * 1.05 ** years
yearly_return_round = [round(value, 2) for value in yearly_return]
print(yearly_return)
print(yearly_return_round)
print(f"At the end of 10 years the balance is: R{round(yearly_amounts[-1], 2)}")

print(f"The difference in % at the end of = {round(((yearly_amounts[-1] - 1000)/ 1000) * 100, 2)}")

Yearly changes
[1050.0, 1102.5, 1157.625, 1215.5062500000001, 1276.2815625000003, 1340.0956406250004, 1407.1004226562504, 1477.455443789063, 1551.3282159785163, 1628.8946267774422]
[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]
[1050.0, 1102.5, 1157.63, 1215.51, 1276.28, 1340.1, 1407.1, 1477.46, 1551.33, 1628.89]
At the end of 10 years the balance is: R1628.89
The difference in % at the end of = 62.89
